In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Netflix Dataset/combinedNetflixData (2).txt",header=None,usecols=[0,1],names=["CustID","Ratings"])

In [ ]:
df

           CustID  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [ ]:
#Checking all the movie id present in our data
movie_count=df[df['CustID'].str.contains(':')].count()[0]

<ipython-input-67-028004c26765>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movie_count=df[df['CustID'].str.contains(':')].count()[0]

In [ ]:
movie_count

4499

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 2 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Ratings  float64
dtypes: float64(1), object(1)
memory usage: 367.1+ MB

In [ ]:
#Number of uniques customer id in our data
cust_count=df['CustID'].nunique()

In [ ]:
cust_count   #In this total custome id count and the movie id will be also counted.

475257

In [ ]:
cust_count=cust_count-movie_count
cust_count

470758

In [ ]:
#Total number of ratings in our data that ar given by users[From total count-count of NAN that is no of movies]
ratings_count=len(df)-movie_count
ratings_count

24053764

In [ ]:
#Lets just make a clear dataframe to find how many movie id are there
#for every row in CustID we will run a loop and select the row where we have colon
#and then store it in y after replacing colon with nothing "".
movie_np=[]
for x in df['CustID']:
  if ':' in x:
    y=x.replace(':',"")
  movie_np.append(y)

In [ ]:
movie_np

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 ...]

In [ ]:
df['MovieID']=movie_np

In [ ]:
df

           CustID  Ratings MovieID
0              1:      NaN       1
1         1488844      3.0       1
2          822109      5.0       1
3          885013      4.0       1
4           30878      4.0       1
...           ...      ...     ...
24058258  2591364      2.0    4499
24058259  1791000      2.0    4499
24058260   512536      5.0    4499
24058261   988963      3.0    4499
24058262  1704416      3.0    4499

[24058263 rows x 3 columns]

In [ ]:
# To keep only the rows where the rating column is not null ( example It exclude rows whete the Rating is NaN)
df.dropna(inplace=True)

In [ ]:
df

           CustID  Ratings MovieID
1         1488844      3.0       1
2          822109      5.0       1
3          885013      4.0       1
4           30878      4.0       1
5          823519      3.0       1
...           ...      ...     ...
24058258  2591364      2.0    4499
24058259  1791000      2.0    4499
24058260   512536      5.0    4499
24058261   988963      3.0    4499
24058262  1704416      3.0    4499

[24053764 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Ratings  float64
 2   MovieID  object
dtypes: float64(1), object(2)
memory usage: 734.1+ MB

In [ ]:
df['CustID']=df['CustID'].astype(int)
df['MovieID']=df['MovieID'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   int64
 1   Ratings  float64
 2   MovieID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
#Manual Filteration
#I want to get the count of every customer with respect to ratings
data_cust_summary=df.groupby('CustID')['Ratings'].count()
data_cust_summary

CustID
6          153
7          195
8           21
10          49
25           4
          ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62
Name: Ratings, Length: 470758, dtype: int64

In [ ]:
cust_benchmark=round(data_cust_summary.quantile(0.60))
# I will select only those customers who have seen more than 36 movies.
cust_benchmark

36

In [ ]:
rejected_cust=data_cust_summary[data_cust_summary<cust_benchmark].index
# When we use groupby fxn the column becomes index
rejected_cust

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustID', length=282042)

In [ ]:
#Filtering our movie data
#First we will get the count of ratings for evry movie.
data_movie_summary=df.groupby('MovieID')['Ratings'].count()

In [ ]:
data_movie_summary

MovieID
1        547
2        145
3       2012
4        142
5       1140
        ...
4495     614
4496    9519
4497     714
4498     269
4499     428
Name: Ratings, Length: 4499, dtype: int64

In [ ]:
movie_benchmark=round(data_movie_summary.quantile(0.60))
movie_benchmark

908

In [ ]:
rejected_movies=data_movie_summary[data_movie_summary<movie_benchmark].index
rejected_movies

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='MovieID', length=2699)

In [ ]:
# Now we have selected the customers and movies that we need to reject.
# Now we will update the result in our actual dataframe (removing these rejected values)

In [ ]:
len(rejected_cust)

282042

In [ ]:
#So this line keeps only the rows where the movie ID cust_ID is NOT in the rejected_movies and rejected_cust list.
df=df[~df['MovieID'].isin(rejected_movies)]
df=df[~df['CustID'].isin(rejected_cust)]

In [ ]:
df

           CustID  Ratings  MovieID
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
700        656399      4.0        3
...           ...      ...      ...
24056842  1055714      5.0     4496
24056843  2643029      4.0     4496
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496

[19695836 rows x 3 columns]

In [ ]:
# Final data that we are left behind is 1 crore 96 lakh 95 thousand 8 hundred thirty six

## Model Building

In [ ]:
# Load the second dataset for movie names as with previous dataset we only have movie id
df_title=pd.read_csv("/content/drive/MyDrive/Netflix Dataset/NetflixMovieData.csv",encoding="ISO-8859-1",header=None,usecols=[0,1,2],names=["Movie_ID","Year","Name"])

In [ ]:
df_title

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [ ]:
! pip install surprise

Requirement already satisfied: surprise in /usr/local/lib/python3.11/dist-packages (0.1)
Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.11/dist-packages (from surprise) (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise->surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise->surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise->surprise) (1.13.1)

In [ ]:
from surprise import SVD , Reader , Dataset

In [ ]:
from surprise.model_selection import cross_validate

In [ ]:
# We only work with top 100k records for quick runtime
data = Dataset.load_from_df(df[['CustID','MovieID','Ratings']][:1000000],reader)

In [ ]:
data

In [ ]:
model=SVD()  # Creating a SVD model

In [ ]:
cross_validate(model ,data , measures=["RMSE"],cv=3)     #Training the SVD model with top 100k data

{'test_rmse': array([0.96984478, 0.96908219, 0.96826807]),
 'fit_time': (16.099467515945435, 17.162177801132202, 17.141568422317505),
 'test_time': (4.45976185798645, 3.5514142513275146, 3.1660189628601074)}

In [ ]:
df

           CustID  Ratings  MovieID
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
700        656399      4.0        3
...           ...      ...      ...
24056842  1055714      5.0     4496
24056843  2643029      4.0     4496
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496

[19695836 rows x 3 columns]

## Recommendation

In [ ]:
# Filter the data for finding a specific user 1331154 to whom we are going to suggest the movies
user_ratings=df[df["CustID"]==1331154 ]
user_ratings

           CustID  Ratings  MovieID
697       1331154      4.0        3
5178      1331154      4.0        8
31460     1331154      3.0       18
92840     1331154      4.0       30
224761    1331154      3.0       44
...           ...      ...      ...
23439584  1331154      4.0     4389
23546489  1331154      2.0     4402
23649431  1331154      4.0     4432
23844441  1331154      3.0     4472
23985561  1331154      4.0     4488

[253 rows x 3 columns]

In [ ]:
# User 1331154 have rated 253 movies

In [ ]:
# Make a copy of each individual customer for recommnedation
user_1331154=df_title.copy()
user_1331154

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [ ]:
# Remove the less rates movies from 2nd dataset also
user_1331154 = user_1331154[~user_1331154["Movie_ID"].isin(rejected_movies)]

In [ ]:
user_1331154

       Movie_ID    Year                                               Name
2             3  1997.0                                          Character
4             5  2004.0                           The Rise and Fall of ECW
5             6  1997.0                                               Sick
7             8  2004.0                         What the #$*! Do We Know!?
15           16  1996.0                                          Screamers
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[15070 rows x 3 columns]

In [ ]:
# Prediction part
user_1331154["Estimated_Score"]= user_1331154["Movie_ID"].apply(lambda x:model.predict(1331154 ,x).est)

<ipython-input-116-4e743d227b2e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_1331154["Estimated_Score"]= user_1331154["Movie_ID"].apply(lambda x:model.predict(1331154 ,x).est)

In [ ]:
user_1331154

,Movie_ID,Year,Name,Estimated_Score
2,3,1997.0,Character,4.235524
4,5,2004.0,The Rise and Fall of ECW,4.259225
5,6,1997.0,Sick,3.570293
7,8,2004.0,What the #$*! Do We Know!?,3.657449
15,16,1996.0,Screamers,3.302752
...,...,...,...,...
17764,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.940672
17765,17767,2004.0,Fidel Castro: American Experience,3.940672
17766,17768,2000.0,Epoch,3.940672
17767,17769,2003.0,The Company,3.940672
17768,17770,2003.0,Alien Hunter,3.940672

In [ ]:
# Display top 5 movies with highest estimates score that user 1331154 can like ?
user_1331154.sort_values("Estimated_Score",ascending=False)

,Movie_ID,Year,Name,Estimated_Score
247,248,2001.0,Michael Moore's The Awful Truth: Season 2,4.880968
208,209,1996.0,Star Trek: Deep Space Nine: Season 5,4.833874
67,68,2004.0,Invader Zim,4.769783
222,223,2003.0,Chappelle's Show: Season 1,4.671793
132,133,2003.0,Viva La Bam: Season 1,4.645760
...,...,...,...,...
110,111,2003.0,Duplex (Widescreen),3.123918
187,188,2005.0,Dead Birds,2.881144
121,122,2002.0,Cube 2: Hypercube,2.760418
126,127,1987.0,Fatal Beauty,2.640960
180,181,2004.0,The Last Shot,2.563493

In [ ]:
user_1331154.head(5)

    Movie_ID    Year                        Name  Estimated_Score
2          3  1997.0                   Character         4.235524
4          5  2004.0    The Rise and Fall of ECW         4.259225
5          6  1997.0                        Sick         3.570293
7          8  2004.0  What the #$*! Do We Know!?         3.657449
15        16  1996.0                   Screamers         3.302752